module.exports = {
  INICIAR_SESION: '#react-root > div > div > div > main > div > div > div > div:nth-child(1) > div > div.css-1dbjc4n > a.css-4rbku5.css-18t94o4.css-1dbjc4n.r-1niwhzg.r-p1n3y5.r-sdzlij.r-1phboty.r-rs99b7.r-1loqt21.r-1w2pmg.r-ku1wi2.r-1jayybb.r-17bavie.r-1ny4l3l.r-15bsvpr.r-o7ynqc.r-6416eg.r-lrvibr',
  USUARIO_INPUT: '[name="session[username_or_email]"][type="text"]',
  CLAVE_INPUT: '[name="session[password]"][type="password"]',
  SESSION_SUBMIT: '[role="button"][data-testid="LoginForm_Login_Button"]',
  ACCESO_CUENTA: 'form[action="/account/access"]',
  POST_BUTTON: '#react-root > div > div > div.css-1dbjc4n.r-18u37iz.r-13qz1uu.r-417010 > header > div > div > div > div:nth-child(1) > div.css-1dbjc4n.r-1awozwy.r-jw8lkh.r-e7q0ms > a',
  MENU_BOTON: '#react-root > div > div > div.css-1dbjc4n.r-18u37iz.r-13qz1uu.r-417010 > header > div > div > div > div.css-1dbjc4n.r-1awozwy.r-zg41ew > div > div',
  CONFIRMAR_CERRAR_SESION: '[data-testid=confirmationSheetConfirm]',
  UPLOAD_INPUT: '#react-root > div > div > div.r-1d2f490.r-u8s1d.r-zchlnj.r-ipm5af.r-184en5c input',
  MESSAGE_INPUT: '#react-root div.DraftEditor-editorContainer > div',
  POST_SUBMIT: 'div.css-18t94o4.css-1dbjc4n.r-urgr8i.r-42olwf.r-sdzlij.r-1phboty.r-rs99b7.r-1w2pmg.r-19u6a5r.r-ero68b.r-1gg2371.r-1ny4l3l.r-1fneopy.r-o7ynqc.r-6416eg.r-lrvibr',
  POST_LINKS: 'div.css-1dbjc4n.r-1d09ksm.r-18u37iz.r-1wbh5a2 > a',
  PIDE_TELEFONO: '#challenge_response',
  ENVIA_TELEFONO: '#email_challenge_submit',
  ALERT: 'div [role=dialog] [role=alert]',
}